import React,{useEffect,useState} from 'react';
import {BrowserOAuthClient} from '@atproto/oauth-client-browser';
const s={fs:{background:'#000',color:'#0f0',height:'100vh',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',fontFamily:'monospace',textAlign:'center'},btn:{padding:'20px',background:'#111',color:'#0f0',border:'1px solid #0f0',cursor:'pointer',margin:'5px'},gBtn:{padding:'20px',background:'#111',color:'#f0f',border:'1px solid #f0f',cursor:'pointer',margin:'5px'}};
export default function App(){
const [c,setC]=useState(null);const [sess,setSess]=useState(null);const [v,setV]=useState('hub');
useEffect(()=>{const client=new BrowserOAuthClient({handleResolver:'https://bsky.social',clientMetadata:'https://quips.cc/client-metadata.json'});client.init().then(r=>{if(r?.session)setSess(r.session);setC(client);});},[]);
if(v==='germ')return(<div style={{...s.fs,color:'#f0f'}}><h1>[ GERM_NET_P2P ]</h1><p>> STATUS: ENCRYPTING...</p><button onClick={()=>setV('hub')} style={{color:'#f0f'}}>BACK</button></div>);
if(v==='bats')return(<div style={s.fs}><h1>[ BATS_OS ]</h1><button onClick={()=>setV('hub')} style={{color:'#0f0'}}>BACK</button></div>);
return(<div style={{background:'#050505',color:'#0f0',minHeight:'100vh',padding:'20px',fontFamily:'monospace',textAlign:'center'}}><h1 style={{fontSize:'3rem',borderBottom:'2px solid #0f0'}}>quips</h1>{!sess?(<div style={{marginTop:'50px'}}><input id='h' type='text' placeholder='handle' style={{background:'#000',color:'#0f0',border:'1px solid #0f0'}} /><button onClick={()=>c?.signIn(document.getElementById('h').value)} style={{marginLeft:'10px',background:'#0f0'}}>START</button></div>):(<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'10px',marginTop:'40px'}}><button onClick={()=>setV('bats')} style={s.btn}>BATS</button><button onClick={()=>setV('germ')} style={s.gBtn}>GERM_NET</button><button onClick={()=>{localStorage.clear();window.location.reload();}} style={s.btn}>LOGOUT</button></div>)}</div>);}
